name: 'terraform'

on:
 push:
  branches: [ "m" ]
 pull_request:
   
permissions: 
 id-token: 'write'
 contents: read

jobs:
  terraform:
   name: 'terraform'
   runs-on: ubuntu-latest

   defaults:
     run:
       shell: bash

    
   steps:
      - name: checkout
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v2.0.0
        with:
         workload_identity_provider: ''
         service_account: ''

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1  

      - name: Terraform Init
        run: terraform init
  
  
      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan -input=false
  
  
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false


         
 
          

   
