name: terraform automation to create s3 bucket

on:
 pull_request:
   branches:
    - main
 push:    
   paths: 
    - 'main.tf'
  
 workflow_dispatch:
 
 

permissions:
 id-token: write
 contents: write

jobs:
  terraform_s3_builb:
   runs-on: ubuntu-latest

   steps:
     - name: checkout source
       uses: actions/checkout@v4
     - name: configuring aws credentials using OIDC
       uses: aws-actions/configure-aws-credentials@v4.1.0
       with:
         aws-region: ap-south-1
         role-to-assume: ${{ secrets.OIDC_TOKEN_GITHUB }}
     - name: test aws credentals
       run: aws sts get-caller-identity        


        
         


  

  

  

 


   
