name: terraform automation to create s3 bucket

on:
 pull_request:
   branches:
    - main
 push:    
   paths: 
    - 'terraform/**'
  
 workflow_dispatch:
 
 

permissions:
 id-token: write
 contents: write

jobs:
  terraform_s3_builb:
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       working-directory: ./terraform

   steps:
     - name: checkout repository
       uses: actions/checkout@v4
       with:
         fetch-depth: 0

     - name: configure the aws credentials
       uses: aws-actions/configure-aws-credentials@v4.1.0
       with:
         aws-region: ap-south-1
         role-to-assume: ${{secrets.OIDC_TOKEN_GITHUB}}
         
         

     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v3
       with:
         terraform_version: 1.4.1

     - name: Terraform format
       id: fmt
       run: terraform fmt -check
    
     - name: Terraform validate
       id: validate
       run: terraform validate
 
     - name: Terraform plan
       id: plan
       if: github.event_name == 'pull_request'
       run: terraform plan -no-color -input=false
       continue-on-error: true

        
         


  

  

 


   
