name: Testing wordflow varibles

on:
 workflow_dispatch

env:
 cloud: google-cloud

jobs:
 greeting_job:
   runs-on: ubuntu-latest
   env:
     Greeting: Hello
    steps:
    - name: "says hello vinay its monday"
      run: echo "$Greeting $Firstname is using $cloud"
      env:
        Firstname: vinay
      

    
