name: testing userinput varibles

on:
 workflow_dispatch:
   inputs:
     number1:
      description: "first number"
      default: '0'
      required: true
     number2:
      description: "second number"
      default: '0'
      required: true

jobs:
  add_number:
   runs-on: ubuntu-latest

   steps:
     - name: add number
       id: sum
       run: echo "::set.output name=sum::$((${{ inputs.number1 }} + ${{inputs.number2}}))"

     - name: Display sum
       run:  echo "the sum of ${{ inputs.number1 }} and ${{ inputs.number2 }} id ${{ steps.sum.outputs.sum }}"
